=== diorcety/jaxb-xew-plugin/src/test/resources/com/sun/tools/xjc/addon/xew/map.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
		jaxb:version="2.0"
		xmlns:jaxb="http://java.sun.com/xml/ns/jaxb"
		xmlns:xew="http://github.com/jaxb-xew-plugin"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema"
		jaxb:extensionBindingPrefixes="xew"
		elementFormDefault="qualified"
>
	<xsd:annotation>
		<xsd:appinfo>
			<jaxb:schemaBindings>
				<jaxb:package name="map"/>
			</jaxb:schemaBindings>
		</xsd:appinfo>
	</xsd:annotation>

	<xsd:element name="message">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="data">
					<xsd:annotation>
						<xsd:appinfo>
							<xew:xew toMap="key,value"/>
						</xsd:appinfo>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="entry" minOccurs="0" maxOccurs="unbounded">
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="key" minOccurs="0" type="xsd:string"/>
										<xsd:element name="value" minOccurs="0" type="xsd:string"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== diorcety/jaxb-xew-plugin/src/test/resources/com/sun/tools/xjc/addon/xew/map.xml
<?xml version="1.0" encoding="UTF-8"?>

<message xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="map.xsd">
	<data>
		<entry>
			<key>id123</key>
			<value>this is a value</value>
		</entry>
		<entry>
			<key>id312</key>
			<value>this is another value</value>
		</entry>
	</data>
</message>
